Student merging backend
klassenteiler/Klassenteiler pull request #46
Opened 2021-02-02 23:36 UTC by antonlaukemper

I changed something in the beforeEach of the surveyController specs which led to an interesting error that needs to be investigated:
![grafik](https://user-images.githubusercontent.com/20592710/106676680-a6fdbf00-65b7-11eb-9339-22d9cfc6be2f.png)

(BTW thank you @rauwuckl  for putting in those logs or this would have failed silently!!)
I am assuming this is a minor error somewhere in the tests, but it should still not be ignored

2021-02-03 15:32 UTC, rauwuckl requested changes
Amazing tests. Love it so much <3

2021-02-03 15:32 UTC, rauwuckl commented on Backend/scala-backend/app/controllers/SurveyController.scala
> +    creationSuccess.flatMap(cSuccess => {
flatten out
on the LHS of 228: val renameSuccess: Future[Boolean] = creationSucess.flatMap(...
...
return on line 238
})

2021-02-03 15:32 UTC, rauwuckl commented on Backend/scala-backend/app/models/StudentModel.scala
> +    updateOp.map(x => println(x))
print

2021-02-03 18:02 UTC, antonlaukemper commented
Ein dutzend neuer commits :D

2021-02-04 10:36 UTC, rauwuckl approved these changes
LGTM

2021-02-04 10:36 UTC, merged